### ISSUE TITLE
City updated website and is no longer compatible

### ISSUE THREAD

**Issue by kateriley** [tallcoleman/tor-rec-sched-to-cal#2]
I absolutely love this script! Unfortunately it looks like the city has revamped their website and now the script no longer works. I have tried parsing out the element from the new site but it is really hard for a beginner without being able to reference the old site for comparison. Any chance you will update to match the new sites? Or have any tips on how to update? 

Either way thanks for all your work.

-Kate

**Comment by tallcoleman** [comment]
I don't know why I wasn't able to find it at the time, but there's actually an API service through the City's Open Data portal here: https://open.toronto.ca/dataset/registered-programs-and-drop-in-courses-offering/

If I have time this weekend, I'll see if I can swap out the source for the script to use the JSON output for the drop-in programs.

**Comment by tallcoleman** [comment]
So I remember these notes later for the schema from https://open.toronto.ca/dataset/registered-programs-and-drop-in-courses-offering/

```json
{
    "_id": 209, // auto-generated for dataset, can ignore
    "Location ID": 17, // keep
    "Course_ID": 7565079, // not discoverable on City website, so will still have to filter by Course Title
    "Course Title": "Lane Swim", // keep
    "Age Min": "84", // in months - no longer a freeform text field. May need to add a feature to help filter out programs with irrelevant age ranges for the user. 
    "Age Max": "None", // same as above
    "Date From": "20241103", // this is the "schedule week starts" date, not the date of the program
    "Date Range": "Nov 3 to Nov 9", // "schedule week" description
    "Start Date Time": "2024-11-07T15:10:00", // this is the datetime the program starts... not tz-aware, so coerce to "America/Toronto"?
    "Start Hour": 15, // two options for these 4 fields: (a) parse hour & min here instead of using time above for the datetime pair (b) calculate duration to generate second datetime for program end. Check for midnight and DST crossover (seems unlikely, but you never know).
    "Start Minute": 10,
    "End Hour": 15,
    "End Min": 55,
    "Category": "Swimming", // double check still the same as program_type before
    "First Date": "2024-10-07", // date range of the entire schedule posting - can ignore?
    "Last Date": "2024-12-29" // date range of the entire schedule posting - can ignore?
  },
```

**Comment by kateriley** [comment]
Oh wow thank you for looking into it and sending through those resources! This dataset website is really cool, I am just trying to figure all this stuff out and this is so helpful.

**Comment by tallcoleman** [comment]
@kateriley should be fixed now with updated script. You'll have to re-do the config you were using since it uses slightly different parameters to get the programs of interest.

**Comment by kateriley** [comment]
This worked beautifully! Thank you so much :)

**Comment by tallcoleman** [comment]
@kateriley you may have noticed the City hasn't updated their Open Data set in several months. I added a fallback to use the website API instead, if you want to use it, please see the details in #6

**Comment by kateriley** [comment]
I did notice that everything was out of date. Thanks so much for reaching out with the solution!

Cheers!

Kate Riley | Business Systems Analyst
(she/her)

Cambridge Forums Inc.
M: +1 <+1-416-703-1577> 647 550 2694
E: ***@***.******@***.***>
W: www.cambridgeforums.com<http://www.cambridgeforums.com/>

Cambridge Forums, 55 University Avenue, Suite 550, Toronto, ON, M5J 2H7

**Comment by kateriley** [comment]
I implemented the fix and it worked beautifully. Thank you so much!

Cheers!

Kate Riley | Business Systems Analyst
(she/her)

Cambridge Forums Inc.
M: +1 <+1-416-703-1577> 647 550 2694
E: ***@***.******@***.***>
W: www.cambridgeforums.com<http://www.cambridgeforums.com/>

Cambridge Forums, 55 University Avenue, Suite 550, Toronto, ON, M5J 2H7


From: Kate Riley
Sent: March 24, 2025 9:03 AM
To: tallcoleman/tor-rec-sched-to-cal ***@***.***>; tallcoleman/tor-rec-sched-to-cal ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [tallcoleman/tor-rec-sched-to-cal] City updated website and is no longer compatible (Issue #2)

I did notice that everything was out of date. Thanks so much for reaching out with the solution!

Cheers!

Kate Riley | Business Systems Analyst
(she/her)

Cambridge Forums Inc.
M: +1 <+1-416-703-1577> 647 550 2694
E: ***@***.******@***.***>
W: www.cambridgeforums.com<http://www.cambridgeforums.com/>

Cambridge Forums, 55 University Avenue, Suite 550, Toronto, ON, M5J 2H7
